### ISSUE TITLE
1920 x 1080 not working in Virtual box

### ISSUE THREAD

**Issue by hardliner66** [tinkeros/TinkerOS#4]
I wanted to play around with TinkerOS a bit, but it says my "Hardware" doesn't support the selected resolution. But with VirtualBox it should be supported.

**Comment by tinkeros** [comment]
None of the virtual display devices in VirtualBox support a 16:9 (or 16:10) **VBE** display modes.   I understand you can run other operating systems inside VirtualBox at 1920x1080, but that is only because they have a display driver.  TempleOS / TinkerOS do not have a display driver and instead uses legacy BIOS function calls to set the display mode.  I've run 1920x1080 on real hardware and also on QEMU.  This is a VirtualBox specific problem.  For whatever reason Oracle simply chooses not to include 16:9 and 16:10 VBE mode resolutions in their VirtualBox virtual display devices while many real video cards and QEMU do.
