### ISSUE TITLE
Toshiba Satellite C655 halt problem

### ISSUE THREAD

**Issue by ChaboCode** [tinkeros/TinkerOS#5]
I bougth a Toshiba Satellite C655 for trying TempleOS, and I didn't know why it stopped always after 5 minutes. I then read your README to figure out the problem. Where can I search information to fix this?

**Comment by clarking** [comment]
Hi, i'm pretty sure you are overheating, TempleOs doesn't know about sensors and temperatures, maybe you are hitting the temp limit and the laptop chooses to protect itself by shutting down, there's no recommendation here aside from implementing the missing functionality, in the meantime you can use a virtual machine inside your preferred Os.

**Comment by ChaboCode** [comment]
Ok, where can I find information to implement that functionality?

**Comment by tinkeros** [comment]
Major manufacturers are not open source friendly and do not release documentation on their hardware necessary to write drivers.  It might be possible someone else has already written code in the Linux kernel which fixes your issue which you would have to find and port to TOS/HolyC.  TOS is meant to run on a certain period of hardware that has minimal dependencies.  Adding code to support specific hardware from specific manufacturers because they decided to add additional requirements for running a baremetal OS is beyond the scope of this project and would cause it to be filled with bloat.  Obviously you're free to fork it, root cause the issue,  reverse engineer everything necessary to get it running and write the appropriate HolyC code yourself if you so desire to do so.  If you do so and find that your changes apply to a significant number of machines allowing TOS to run on many more systems, then please make a pull request.

**Comment by tinkeros** [comment]
@ChaboCode This now is resolved on my laptop.  It seemed to be related to the kernel trying to initialize the HPET.  I've removed the HPET support and now it works for me with no crashes.
